package com.mhmtn.a6thsense.core.domain

import androidx.annotation.StringRes
import com.mhmtn.a6thsense.R


enum class Option(@StringRes val displayNameRes: Int) {
    // Phase 1
    A(R.string.option_a),
    B(R.string.option_b),

    // Phase 2 - Colors
    RED(R.string.color_red),
    BLUE(R.string.color_blue),
    GREEN(R.string.color_green),
    YELLOW(R.string.color_yellow),
    PURPLE(R.string.color_purple),
    ORANGE(R.string.color_orange),
    PINK(R.string.color_pink),
    CYAN(R.string.color_cyan),
    MAGENTA(R.string.color_magenta),
    LIME(R.string.color_lime),
    TEAL(R.string.color_teal),
    CORAL(R.string.color_coral),
    INDIGO(R.string.color_indigo),
    MINT(R.string.color_mint),
    LAVENDER(R.string.color_lavender),
    GOLD(R.string.color_gold),
    SILVER(R.string.color_silver),
    BRONZE(R.string.color_bronze),
    EMERALD(R.string.color_emerald),
    RUBY(R.string.color_ruby),
    SAPPHIRE(R.string.color_sapphire),
    AMBER(R.string.color_amber),
    TURQUOISE(R.string.color_turquoise),
    VIOLET(R.string.color_violet),
    BEIGE(R.string.color_beige),
    MAROON(R.string.color_maroon),
    OLIVE(R.string.color_olive),
    NAVY(R.string.color_navy),
    SLATE(R.string.color_slate),
    CRIMSON(R.string.color_crimson),
    CHARCOAL(R.string.color_charcoal),
    IVORY(R.string.color_ivory),

    // Phase 3 - Animals
    LION(R.string.animal_lion),
    EAGLE(R.string.animal_eagle),
    DOLPHIN(R.string.animal_dolphin),
    WOLF(R.string.animal_wolf),
    TIGER(R.string.animal_tiger),
    OWL(R.string.animal_owl),
    BUTTERFLY(R.string.animal_butterfly),
    BEAR(R.string.animal_bear),
    HORSE(R.string.animal_horse),
    SNAKE(R.string.animal_snake),
    PHOENIX(R.string.animal_phoenix),
    FOX(R.string.animal_fox),
    DRAGON(R.string.animal_dragon),
    WHALE(R.string.animal_whale),
    HAWK(R.string.animal_hawk),
    PEACOCK(R.string.animal_peacock),
    CAT(R.string.animal_cat),
    DOG(R.string.animal_dog),
    RABBIT(R.string.animal_rabbit),
    DEER(R.string.animal_deer),
    SHARK(R.string.animal_shark),
    OCTOPUS(R.string.animal_octopus),
    RAY(R.string.animal_ray),
    TURTLE(R.string.animal_turtle),
    BAT(R.string.animal_bat),
    SCORPION(R.string.animal_scorpion),
    SPIDER(R.string.animal_spider),
    RAVEN(R.string.animal_raven),
    SWAN(R.string.animal_swan),
    HUMMINGBIRD(R.string.animal_hummingbird),
    KOALA(R.string.animal_koala),
    PANDA(R.string.animal_panda),

    // Phase 4 - Elements & Nature
    FIRE(R.string.nature_fire),
    WATER(R.string.nature_water),
    EARTH(R.string.nature_earth),
    AIR(R.string.nature_air),
    LIGHTNING(R.string.nature_lightning),
    ICE(R.string.nature_ice),
    FOREST(R.string.nature_forest),
    DESERT(R.string.nature_desert),
    MOUNTAIN(R.string.nature_mountain),
    OCEAN(R.string.nature_ocean),
    VOLCANO(R.string.nature_volcano),
    WIND(R.string.nature_wind),
    RAIN(R.string.nature_rain),
    SNOW(R.string.nature_snow),
    SUN(R.string.nature_sun),
    MOON(R.string.nature_moon),
    STORM(R.string.nature_storm),
    THUNDER(R.string.nature_thunder),
    CLOUD(R.string.nature_cloud),
    FOG(R.string.nature_fog),
    RIVER(R.string.nature_river),
    LAKE(R.string.nature_lake),
    CAVE(R.string.nature_cave),
    CANYON(R.string.nature_canyon),
    STAR(R.string.nature_star),
    GALAXY(R.string.nature_galaxy),
    NEBULA(R.string.nature_nebula),
    COMET(R.string.nature_comet),
    LEAF(R.string.nature_leaf),
    FLOWER(R.string.nature_flower),
    ROOT(R.string.nature_root),
    SEED(R.string.nature_seed),

    // Phase 5 - Dimensions & Abstract
    LIGHT(R.string.abstract_light),
    DARK(R.string.abstract_dark),
    TIME(R.string.abstract_time),
    SPACE(R.string.abstract_space),
    ENERGY(R.string.abstract_energy),
    GRAVITY(R.string.abstract_gravity),
    INFINITY(R.string.abstract_infinity),
    VOID(R.string.abstract_void),
    COSMOS(R.string.abstract_cosmos),
    QUANTUM(R.string.abstract_quantum),
    DIMENSION(R.string.abstract_dimension),
    PARALLEL(R.string.abstract_parallel),
    PAST(R.string.abstract_past),
    FUTURE(R.string.abstract_future),
    PRESENT(R.string.abstract_present),
    ETERNITY(R.string.abstract_eternity),
    MIND(R.string.abstract_mind),
    SOUL(R.string.abstract_soul),
    SPIRIT(R.string.abstract_spirit),
    BODY(R.string.abstract_body),
    DREAM(R.string.abstract_dream),
    REALITY(R.string.abstract_reality),
    TRUTH(R.string.abstract_truth),
    ILLUSION(R.string.abstract_illusion),
    ORDER(R.string.abstract_order),
    CHAOS(R.string.abstract_chaos),
    HARMONY(R.string.abstract_harmony),
    DISCORD(R.string.abstract_discord),
    WISDOM(R.string.abstract_wisdom),
    KNOWLEDGE(R.string.abstract_knowledge),
    INSTINCT(R.string.abstract_instinct),
    REASON(R.string.abstract_reason)
}
